name: calculator
description: "Demo calculator app"
publish_to: 'none'
version: 0.1.0
repository: "https://github.com/Yakiyo/calculator"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.6.0
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
